---
title: "Business Analytics"
author: "Matt Rissler"
date: "`r format(Sys.Date())`"
output: 
  ioslides_presentation:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE)
library(network)
library(sna)
library(ggnetwork)
library(tidyverse)
library(forcats)
library(grid)
```

## The Major

```{r PreReqs, include=FALSE}
courses <- c("MAT 150", "ACC 227", "BUS 230", "BUS 240", "BUS 350", "CIT 115",
             "CIT 225", "CIT 321", "CIT 340", "MAT 220", "BAN 210", "BAN 220", 
             "BAN 330", "BAN 340", "BAN 450", "BAN 460", "BAN 490")
n<-network.initialize(17)
network.vertex.names(n)<- courses


 locations<-matrix(
   c( 0.15, 0.25,   0.85, 0.3,   0.85, 1.55,   0.75, 1.25,   1, 1,   0.5, 0.25,
      0.45, 1,    1, 1.5,    .3, 2.9,   0.15, 1,    0.65, 0.75,   1, 2.2,
      0, 2.35,   0.9, 3,    0.65, 3.4,   0.45, 3.4,        0.5, 4), 
   ncol=2, byrow = TRUE)
PreReqs <- data.frame(needed_id= parse_factor(c("MAT 150", "CIT 115",
                                                "ACC 227", "BUS 230", "BUS 240",
                                                "MAT 220", "CIT 115",
                                                "CIT 115",
                                                "CIT 225",
                                                "CIT 225",
                                                "BAN 210", "BUS 240",
                                                "BAN 210", "BAN 330", "BAN 340"
                                                ),
                                   courses), 
                      for_id=    parse_factor(c(rep("MAT 220",2),
                                                rep("BAN 340", 3),
                                                rep("BAN 330",2),
                                                "CIT 225",
                                                "CIT 340",
                                                "BAN 460",
                                                rep("BAN 450",2),
                                                rep("BAN 490",3)
                                                ),
                                   courses),
                      
                      stringsAsFactors = FALSE
                      )

add.edges(n, PreReqs$needed_id,PreReqs$for_id)
```




```{r plotNetwork, dependson=PreReqs}
net<-ggnetwork(n, layout=locations)

 
g <- rasterGrob(colorRampPalette(c("mediumpurple1", "yellow"))(8), 
                width=unit(1,"npc"), height = unit(1,"npc"), 
                interpolate = FALSE) 
ggplot(net, aes(x = x, y = y, xend = xend, yend = yend))+
  annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
  geom_edges(arrow = arrow(length = unit(7, "pt")), 
             curvature=0.1, size=0.75)+
  geom_nodes()+
  geom_segment(aes(x=x,y=y,xend=xend,yend=yend  ),
               data=tibble(x=c(-0.17), y=c(0), xend=c(-0.17), yend=c(1)),
               arrow=arrow(length = unit(7, "pt") ) )+
  annotate("text", x=-.23, y=.5, label="Time") +
  geom_nodelabel(aes(label=vertex.names))+
  expand_limits(x=c(-.15,1.05))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        legend.key = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        panel.grid = element_blank()
        ) 
  
```

## All? the Worst Cases
```{r worstCase, dependson=PreReqs}
add.vertices(n, 2, vattr=list(list(vertex.names= "MAT 113"),list(vertex.names= "MAT 117")))
courses <- c(courses, "MAT 113", "MAT 117")
add.edge(n, parse_factor(c("MAT 113"),courses), parse_factor(c("MAT 117"),courses ))
add.edge(n, parse_factor(c("MAT 117"),courses), parse_factor(c("MAT 150"),courses ))
add.edge(n, parse_factor(c("MAT 117"),courses), parse_factor(c("CIT 115"),courses ))


locations<-matrix(
   c( 0.25, 1.25,   0.85, 2.25,   0.7, 2.25,   0.53, 2.25,   1, 3.75,   0, 1.25,
      0, 2.25,    0.75, 3.75,    .15, 2.75,   0.25, 1.75,    0.45, 2.75,   0.25, 3.75,
      0.25, 2.25,   0.8, 2.75,    0.56, 3.25,   0.05, 3.25,        0.5, 3.75,  0.25, 0.25,
      0.25, 0.75), 
   ncol=2, byrow = TRUE)
net<-ggnetwork(n, layout=locations)
 
g <- rasterGrob(colorRampPalette(c("mediumpurple1", "yellow"))(8), 
                width=unit(1,"npc"), height = unit(1,"npc"), 
                interpolate = FALSE) 
ggplot(net, aes(x = x, y = y, xend = xend, yend = yend))+
  annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
  geom_edges(arrow = arrow(length = unit(7, "pt")), 
             curvature=0.1, size=0.75)+
  geom_nodes()+
  geom_segment(aes(x=x,y=y,xend=xend,yend=yend  ),
               data=tibble(x=c(-0.17), y=c(0), xend=c(-0.17), yend=c(1)),
               arrow=arrow(length = unit(7, "pt") ) )+
  annotate("text", x=-.23, y=.5, label="Time") +
  annotate("text", x=-.23, y=0, label="Odd Fall")+
  geom_nodelabel(aes(label=vertex.names))+
  expand_limits(x=c(-.15,1.05), y=c(0,1))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        legend.key = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        panel.grid = element_blank()
        ) 
  
```


## Rotation of Classes

If a class does not appear, it is offered every semester.
```{r When, results="asis"}
class_schedule <- data_frame(Code = courses,
                       
                       Title = c("Calc I", "Managerial Accounting", 
                                 "Principles of Management", "Principles of Marketing",
                                 "Principles of Finance", "Programming and Design Basics",
                                 "Data Structures and Algorithms", "Data Analysis",
                                 "Machine Learning", "Prob/Stats",
                                 "Essentials of Analytics", "Data Visualization",
                                 "Intro to Data Science", "Innovation",
                                 "Marketing Analytics", "Big Data Analytics",
                                 "Discovery"), 
                       
                       Semester = c("Every", "Every","Every","Every", "Every", "Every",
                                    "Every", "Springs", "Even Springs", "Springs", "Every", "Springs", 
                                    "Odd Falls", "Springs", "Falls", "Odd Springs", "Springs")
                       )
                       
class_schedule %>% filter(Semester != "Every") %>% slice(1:4) %>%  knitr::kable()

```

## Rotation of Classes

```{r rotation2, results="asis"}
class_schedule %>% filter(Semester != "Every") %>% slice(5:n()) %>%  knitr::kable()
```